server:
  port: 8001

spring:
  application:
    name: shopping-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    port: 6379
    host: 62.234.151.43
    password: Chen1234
logging:
  level:
    root: INFO
    com:
      diony:
        shopping:
          auth: INFO