server:
  port: 8702
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
