swagger: #接口注解文档
  basepackage: com.billow.user.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    description: 警告：此API仅用于测试，禁止任何商业用途，否则一切后果自行承担！！！ #api描述
    contact:
      developer: billow #api开发者
      url: https://github.com/Xiao-Y/learn
      email: lyongtao123@126.com #api开发者

server:
  context-path: /admin-user

spring:
  application:
    name: learn-shop-admin-user #客户端名称
#  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
#    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪
# 如果路由方式是serviceId的方式，那么ribbon的生效，如果是url的方式，则zuul.host开头的生效
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 10000
#安全配置
#security:
#  oauth2:
#    client:
#      client-id: webapp
#      client-secret: webapp
#      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
#      access-token-uri: http://127.0.0.1:9999/oauth/token
#    resource:
#      jwt:
#        key-uri: http://127.0.0.1:9999/oauth/token_key
#      user-info-uri: http://127.0.0.1:9999/user #获取用户信息的地址

# 显示 sql 的查询参数
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE